# Generated by Django 2.1 on 2021-03-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_auto_20210311_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
