# Generated by Django 3.1.1 on 2020-10-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='mpoly',
        ),
    ]
