# Generated by Django 3.1.1 on 2020-10-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified',
        ),
    ]
