# Generated by Django 3.1.1 on 2021-02-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesFact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_sentiment', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'articles_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DateDim',
            fields=[
                ('dateid', models.IntegerField(primary_key=True, serialize=False)),
                ('full_date', models.CharField(blank=True, max_length=20, null=True)),
                ('dd', models.IntegerField(blank=True, null=True)),
                ('mm', models.IntegerField(blank=True, null=True)),
                ('yy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'date_dim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SentimentFact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trading_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('comp_sentiment', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'sentiment_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeDim',
            fields=[
                ('timeid', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, max_length=2, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_dim',
                'managed': False,
            },
        ),
    ]
