# Generated by Django 3.1.1 on 2021-02-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_articlesfact_datedim_sentimentfact_timedim'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaSentimentDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('comp_sentiment', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('sma', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('ema', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'ma_sentiment_dim',
                'managed': False,
            },
        ),
    ]
