# Generated by Django 2.1 on 2021-03-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_sentview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sentview',
            table='sent_view_interval',
        ),
    ]
